version: build-{build}

configuration: Release

image: Ubuntu2204

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_DEPLOY_KEY:
    secure: bfIsyEMzYM9AJCFQwxLjAC48zi8/pNgUokbWcEcEo4hzLvrGCKEN6pNYkQIx/w2J

nuget:
  disable_publish_on_pr: true

before_build:
- dotnet --info
- dotnet restore .\src\DotNetSortRefs.sln

build_script:
- dotnet build .\src\DotNetSortRefs.sln --configuration Release
 
# after_test:
#   - dotnet pack .\src\DotNetSortRefs --configuration Release

# artifacts:
#   - path: '**\dotnet-sort-refs.*.*nupkg' # find all NuGet packages recursively

# deploy:
#   provider: NuGet
#   api_key: $(NUGET_DEPLOY_KEY)
#   artifact: /.*\.nupkg/
#   on:
#     APPVEYOR_REPO_TAG: true

